org.gradle.jvmargs=-Xmx2G -XX:MaxMetaspaceSize=512m -XX:ReservedCodeCacheSize=256m -XX:+HeapDumpOnOutOfMemoryError --enable-native-access=ALL-UNNAMED
android.useAndroidX=true
android.newDsl=false
android.builtInKotlin=false
systemProp.http.connectionTimeout=60000
systemProp.http.socketTimeout=60000
