// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTmYk_6h3AUdONKYGEm0LQ9c-HVEF6XmM',
    appId: '1:97646362122:web:cfadb66d1afe85a37969f3',
    messagingSenderId: '97646362122',
    projectId: 'fitwave-d99c3',
    authDomain: 'fitwave-d99c3.firebaseapp.com',
    storageBucket: 'fitwave-d99c3.firebasestorage.app',
    measurementId: 'G-8M80LS03KL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNZ3xXbyTECMn5fk8qag-3Xx5BMJ4dNo4',
    appId: '1:97646362122:android:57697c86ee49e29c7969f3',
    messagingSenderId: '97646362122',
    projectId: 'fitwave-d99c3',
    storageBucket: 'fitwave-d99c3.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTmYk_6h3AUdONKYGEm0LQ9c-HVEF6XmM',
    appId: '1:97646362122:web:7b490436ee4d5b227969f3',
    messagingSenderId: '97646362122',
    projectId: 'fitwave-d99c3',
    authDomain: 'fitwave-d99c3.firebaseapp.com',
    storageBucket: 'fitwave-d99c3.firebasestorage.app',
    measurementId: 'G-CV4LERKF0N',
  );
}
